export default {
    wave: require('../assests/images/wave.png'),
    cang: require('../assests/images/cang.png'),
    logo: require('../assests/images/logo.png'),
    tau: require('../assests/images/tau.png'),
    chim: require('../assests/images/chim.png'),
    bg: require('../assests/images/bg.png'),
    bglogin: require('../assests/images/bglogin.png'),
    bgregister: require('../assests/images/bgregister.png'),
    xuatnhapben: require('../assests/images/xuatnhapben.png'),
    tauca: require('../assests/images/tauca.png'),
    thuyenvien: require('../assests/images/thuyenvien.png'),
    lichsuvipham: require('../assests/images/lichsuvipham.png'),
    lichsutainan: require('../assests/images/lichsutainan.png'),
    canhbao: require('../assests/images/canhbao.png'),
    avatar: require('../assests/images/avatar.png'),
    avatar1: require('../assests/images/avatar1.png'),
}